Adds gradients and layout design fixes
ApollosProject/apollos-tv pull request #73
Opened 2021-11-22 21:33 UTC by AlonsoChavarriaga

### About
Fixes the gradient on the hero image, and some layout issues with the card carousels

### Screenshots
![Screen Shot 2021-11-22 at 10 33 46 AM](https://user-images.githubusercontent.com/16511774/142938279-c6cf8f4e-070f-4524-810e-24d9751ccacb.png)

2021-11-29 15:59 UTC, jordanwade requested changes
Looking good, just some minor suggestions.

2021-11-29 15:59 UTC, jordanwade commented on shared/components/FeatureFeed/Features/HeroListFeature.js
> +            colors={['#00000000', '#1C1C1EEE', '#1C1C1EE6']}
I don't think we need a three color gradient. Is there a reason for three?

It also looks like the gradient isn't fading the picture out all the way at the bottom.
![image](https://user-images.githubusercontent.com/2528817/143899229-d7ff2e97-2e9d-4335-b9f0-87ff74d5d13f.png)

2021-11-29 15:59 UTC, jordanwade commented on shared/components/FeatureFeed/Features/HeroListFeature.js
> +              height: '200%',
The `height 200%` works, but what do you think about using `paddingBottom: '56.25%'` that is what is being used to set the background image to be 16:9 ratio.

2021-11-29 15:59 UTC, jordanwade commented on shared/components/FeatureFeed/Features/HorizontalCardListFeature.js
> +      <H3 px={responsive({ _: 's', md: 'base' })} mb="xs">
Instead of moving the title and cards to the left, let's move them to the right and align them with the title and description of the HeroListFeature.
<img width="692" alt="Screen Shot 2021-11-29 at 9 54 48 AM" src="https://user-images.githubusercontent.com/2528817/143900349-fcf70a3c-befc-4ea0-bcb9-38c3abed06ef.png">

2021-11-29 15:59 UTC, jordanwade commented on tvappnative/ios/Podfile
> +# post_install do |installer|
Are we sure we need to do this, does your machine work if you revert this? Just wondering if it was just the `Excluded Architectures` that needed to change.

2021-11-29 20:14 UTC, AlonsoChavarriaga commented on tvappnative/ios/Podfile
> +# post_install do |installer|
It does not work if I revert this, but its only a 3 line change so I can revert it and just make that change locally, would that work better?

2021-11-29 20:15 UTC, AlonsoChavarriaga commented on shared/components/FeatureFeed/Features/HeroListFeature.js
> +            colors={['#00000000', '#1C1C1EEE', '#1C1C1EE6']}
I had done the 3 gradients to make it smoother since it was a bit too steep of a gradient with just the two, but I'll work with the colors a bit like we talked about this morning to see if I can get it tighter

2021-11-30 15:08 UTC, jordanwade commented on tvappnative/ios/Podfile
> +# post_install do |installer|
I would say leave it in there that way if anyone else has M1 they don't have to go through trying to fix it. Just wanted to double check the flipper stuff was needed 👍

2021-11-30 15:19 UTC, jordanwade commented
@AlonsoChavarriaga is this ready for another review? Whenever it is feel free to re-request.

2021-11-30 15:45 UTC, AlonsoChavarriaga commented
> @AlonsoChavarriaga is this ready for another review? Whenever it is feel free to re-request.

Yes, thanks! Just re-requested

2021-12-01 16:21 UTC, jordanwade commented
@AlonsoChavarriaga looks like the carousel/Flatlist was still broken I pushed up a commit that uses padding instead of margin and uses `themeGet` and `withTheme` to get the proper spacing. Going to go ahead a merge it now, let me know if you have any questions around my changes. Here is my commit https://github.com/ApollosProject/apollos-tv/pull/73/commits/01be0e685834690bc212efc7a2c9f7af3e564481

![image](https://user-images.githubusercontent.com/2528817/144271764-0eb2f9be-f49c-4f9f-aee9-c7f7f93b0898.png)

2021-12-01 16:22 UTC, merged